# Generated by Django 3.2.7 on 2021-09-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('bloodPressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
    ]
